name: "Deploy"
run-name: Deploying branch ${{ github.base_ref }} on AWS by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
      - ".github/workflows/deploy-sls.yml"

env:
  CI: true
  SLS_DEBUG: false

defaults:
  run:
    working-directory: ./backend
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    name: Deploy serverless to development
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Node and Cache
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache-dependency-path: ./backend/yarn.lock
          cache: yarn

      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile
        shell: bash


      - name: serverless deploy
        shell: bash
        run: yarn sls deploy --stage dev